name: chapter_test
on:
  workflow_dispatch:
    inputs:
      file:
        description: 'The test file name (with extension)'
        required: true
        type: string

jobs:
  test_chapter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.7.2'
      - run: pip install django==2.1.5 pillow==5.4.1
      - name: Run tests
        run: python manage.py test ${{ inputs.file }}